from .event_schema import HistoricalEvent, MarketOutcome


HISTORICAL_EVENTS = [
    HistoricalEvent(
        id="yom-kippur-1973",
        name="Yom Kippur War (1973)",
        description="On October 6, 1973, a coalition of Arab states led by Egypt and Syria launched a surprise attack on Israel on Yom Kippur, the holiest day in Judaism. The war involved direct combat between Israel and Arab forces across the Sinai Peninsula and Golan Heights. The United States initiated a major airlift of military supplies to Israel, while the Soviet Union supported Arab states. OPEC declared an oil embargo against nations supporting Israel, leading to the 1973 oil crisis. Global oil prices quadrupled, causing economic turmoil worldwide. The conflict reshaped Middle Eastern geopolitics and demonstrated the strategic power of oil as a political weapon.",
        date="1973-10-06",
        event_type="conflict",
        entities=["Israel", "Egypt", "Syria", "United States", "Soviet Union", "OPEC", "Arab League", "Golan Heights", "Sinai Peninsula"],
        sectors=["Energy", "Defense", "Transportation", "Manufacturing"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=400.0, volatility=85.0, recovery_days=365),
            MarketOutcome(sector="Defense", impact_pct=15.0, volatility=30.0, recovery_days=120),
            MarketOutcome(sector="Transportation", impact_pct=-12.0, volatility=45.0, recovery_days=180),
            MarketOutcome(sector="Manufacturing", impact_pct=-8.0, volatility=35.0, recovery_days=200),
        ],
        volatility=85.0,
        recovery_days=365,
        summary="Oil prices quadrupled, defense stocks surged, global recession ensued."
    ),
    HistoricalEvent(
        id="iranian-revolution-1979",
        name="Iranian Revolution (1979)",
        description="The Iranian Revolution resulted in the overthrow of the US-backed Shah Mohammad Reza Pahlavi and establishment of an Islamic republic under Ayatollah Khomeini. Iran's oil production collapsed from 6 million barrels per day to under 1.5 million. Global oil prices surged from $13 to $40 per barrel. The US embassy hostage crisis further escalated tensions. Western defense spending increased dramatically. The revolution transformed Iran from a Western ally to a major geopolitical adversary and triggered a fundamental shift in global energy markets and Middle Eastern power dynamics.",
        date="1979-01-16",
        event_type="political",
        entities=["Iran", "United States", "Shah Pahlavi", "Ayatollah Khomeini", "OPEC", "Middle East"],
        sectors=["Energy", "Defense", "Financials"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=200.0, volatility=75.0, recovery_days=300),
            MarketOutcome(sector="Defense", impact_pct=10.0, volatility=25.0, recovery_days=90),
            MarketOutcome(sector="Financials", impact_pct=-5.0, volatility=40.0, recovery_days=150),
        ],
        volatility=75.0,
        recovery_days=300,
        summary="Oil prices tripled, defense stocks rose, global uncertainty spiked."
    ),
    HistoricalEvent(
        id="gulf-war-1990",
        name="Iraq Invasion of Kuwait / Gulf War (1990)",
        description="On August 2, 1990, Iraq under Saddam Hussein invaded and annexed Kuwait, claiming it as a historic province. The invasion triggered immediate UN sanctions and a US-led coalition of 35 nations. Iraq set fire to over 700 Kuwaiti oil wells as they retreated. Oil prices doubled from $15 to $40 per barrel. The conflict demonstrated post-Cold War US military dominance and reshaped Middle Eastern alliances. The war cost an estimated $60 billion but was largely funded by coalition partners. Markets recovered relatively quickly after the coalition victory, but energy markets remained volatile.",
        date="1990-08-02",
        event_type="conflict",
        entities=["Iraq", "Kuwait", "United States", "Saddam Hussein", "UN", "Saudi Arabia", "Coalition Forces"],
        sectors=["Energy", "Defense", "Airlines", "Insurance"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=100.0, volatility=60.0, recovery_days=180),
            MarketOutcome(sector="Defense", impact_pct=20.0, volatility=25.0, recovery_days=60),
            MarketOutcome(sector="Airlines", impact_pct=-15.0, volatility=40.0, recovery_days=120),
            MarketOutcome(sector="Insurance", impact_pct=10.0, volatility=30.0, recovery_days=90),
        ],
        volatility=60.0,
        recovery_days=180,
        summary="Oil prices doubled, defense stocks surged, airlines suffered, insurance hardened."
    ),
    HistoricalEvent(
        id="asian-financial-crisis-1997",
        name="Asian Financial Crisis (1997)",
        description="The Asian Financial Crisis began in Thailand with the collapse of the Thai baht after the government was forced to float the currency due to lack of foreign reserves. The crisis rapidly spread across Southeast Asia and to South Korea, Indonesia, and other Asian economies. Stock markets fell 30-70%, currencies collapsed, and GDP contracted sharply. The IMF intervened with $40 billion in bailouts. Global investors fled emerging markets. The crisis exposed weaknesses in financial systems, pegged currency regimes, and excessive short-term foreign debt. It led to significant reforms in global financial regulation.",
        date="1997-07-02",
        event_type="economic",
        entities=["Thailand", "South Korea", "Indonesia", "Malaysia", "Philippines", "Hong Kong", "IMF", "Japan", "China"],
        sectors=["Financials", "Technology", "Real Estate", "Manufacturing"],
        outcomes=[
            MarketOutcome(sector="Financials", impact_pct=-40.0, volatility=80.0, recovery_days=730),
            MarketOutcome(sector="Technology", impact_pct=-30.0, volatility=60.0, recovery_days=500),
            MarketOutcome(sector="Real Estate", impact_pct=-50.0, volatility=70.0, recovery_days=800),
            MarketOutcome(sector="Manufacturing", impact_pct=-20.0, volatility=50.0, recovery_days=400),
        ],
        volatility=80.0,
        recovery_days=730,
        summary="Asian markets crashed 30-70%, currencies collapsed, IMF bailouts, global contagion."
    ),
    HistoricalEvent(
        id="nine-eleven-2001",
        name="9/11 Terrorist Attacks (2001)",
        description="On September 11, 2001, al-Qaeda terrorists hijacked four commercial airplanes and carried out coordinated suicide attacks against US landmarks. Two planes struck the World Trade Center towers in New York City, causing both to collapse. A third hit the Pentagon in Arlington, Virginia. The fourth crashed in Pennsylvania after passenger resistance. Nearly 3,000 people were killed. The attacks triggered the US War on Terror, invasions of Afghanistan and later Iraq, massive increases in defense and homeland security spending, and fundamental changes in global aviation security. Global markets shut down for days and experienced severe losses upon reopening.",
        date="2001-09-11",
        event_type="conflict",
        entities=["United States", "Al-Qaeda", "Osama Bin Laden", "New York City", "Pentagon", "NATO", "Afghanistan", "Taliban"],
        sectors=["Airlines", "Insurance", "Defense", "Travel & Hospitality", "Technology"],
        outcomes=[
            MarketOutcome(sector="Airlines", impact_pct=-40.0, volatility=70.0, recovery_days=500),
            MarketOutcome(sector="Insurance", impact_pct=-20.0, volatility=65.0, recovery_days=365),
            MarketOutcome(sector="Defense", impact_pct=35.0, volatility=30.0, recovery_days=120),
            MarketOutcome(sector="Travel & Hospitality", impact_pct=-30.0, volatility=55.0, recovery_days=400),
            MarketOutcome(sector="Technology", impact_pct=-10.0, volatility=45.0, recovery_days=180),
        ],
        volatility=75.0,
        recovery_days=500,
        summary="Aviation and insurance devastated, defense surged, war on terror began."
    ),
    HistoricalEvent(
        id="iraq-war-2003",
        name="Iraq War / Operation Iraqi Freedom (2003)",
        description="On March 20, 2003, a US-led coalition invaded Iraq to overthrow Saddam Hussein's regime, citing weapons of mass destruction and links to terrorism. The invasion succeeded within weeks but led to a protracted insurgency and civil war lasting over a decade. Over 4,400 US troops and hundreds of thousands of Iraqis died. The war cost the US over $2 trillion. Oil production in Iraq was disrupted for years. Energy prices rose significantly during the invasion period. The war deepened anti-American sentiment in the Middle East and created power vacuums that contributed to the rise of ISIS.",
        date="2003-03-20",
        event_type="conflict",
        entities=["United States", "Iraq", "Saddam Hussein", "Coalition Forces", "UK", "UN", "ISIS", "Middle East"],
        sectors=["Energy", "Defense", "Airlines", "Construction"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=30.0, volatility=50.0, recovery_days=200),
            MarketOutcome(sector="Defense", impact_pct=25.0, volatility=20.0, recovery_days=90),
            MarketOutcome(sector="Airlines", impact_pct=-8.0, volatility=35.0, recovery_days=150),
            MarketOutcome(sector="Construction", impact_pct=5.0, volatility=15.0, recovery_days=60),
        ],
        volatility=50.0,
        recovery_days=200,
        summary="Oil spiked 30%, defense stocks rallied, prolonged conflict weighed on sentiment."
    ),
    HistoricalEvent(
        id="global-financial-crisis-2008",
        name="Global Financial Crisis (2008)",
        description="The Global Financial Crisis was the most severe worldwide economic disaster since the Great Depression. Triggered by the collapse of the US housing bubble and subprime mortgage crisis, it led to the failure of Lehman Brothers, the bailout of AIG, and government takeovers of Fannie Mae and Freddie Mac. The crisis spread globally through interconnected financial systems. The S&P 500 fell 57% from peak to trough. Global GDP contracted by 2.1% in 2009. Central banks implemented unprecedented monetary policies including quantitative easing. The crisis led to sweeping financial regulatory reforms including Dodd-Frank and Basel III.",
        date="2008-09-15",
        event_type="economic",
        entities=["United States", "Lehman Brothers", "AIG", "Fannie Mae", "Freddie Mac", "Federal Reserve", "European Union", "IMF", "World Bank"],
        sectors=["Financials", "Real Estate", "Manufacturing", "Technology", "Consumer Discretionary"],
        outcomes=[
            MarketOutcome(sector="Financials", impact_pct=-55.0, volatility=90.0, recovery_days=1200),
            MarketOutcome(sector="Real Estate", impact_pct=-40.0, volatility=75.0, recovery_days=1500),
            MarketOutcome(sector="Manufacturing", impact_pct=-25.0, volatility=60.0, recovery_days=800),
            MarketOutcome(sector="Technology", impact_pct=-35.0, volatility=65.0, recovery_days=700),
            MarketOutcome(sector="Consumer Discretionary", impact_pct=-30.0, volatility=55.0, recovery_days=900),
        ],
        volatility=90.0,
        recovery_days=1500,
        summary="Markets crashed 57%, banks failed, global recession, unprecedented central bank intervention."
    ),
    HistoricalEvent(
        id="arab-spring-2011",
        name="Arab Spring Uprisings (2011)",
        description="The Arab Spring was a series of anti-government protests, uprisings, and armed rebellions that spread across much of the Arab world. Beginning in Tunisia in December 2010, it spread to Egypt, Libya, Syria, Yemen, Bahrain, and other countries. Longtime leaders were overthrown in Tunisia, Egypt, Libya, and Yemen. Syria descended into a devastating civil war. Oil prices surged above $120 per barrel due to supply disruptions in Libya and uncertainty across the region. The geopolitical landscape of the Middle East was fundamentally altered, with power vacuums leading to prolonged instability.",
        date="2011-01-14",
        event_type="political",
        entities=["Tunisia", "Egypt", "Libya", "Syria", "Yemen", "Bahrain", "Middle East", "North Africa"],
        sectors=["Energy", "Defense", "Tourism", "Financials"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=40.0, volatility=55.0, recovery_days=250),
            MarketOutcome(sector="Defense", impact_pct=8.0, volatility=20.0, recovery_days=60),
            MarketOutcome(sector="Tourism", impact_pct=-25.0, volatility=50.0, recovery_days=400),
            MarketOutcome(sector="Financials", impact_pct=-10.0, volatility=35.0, recovery_days=200),
        ],
        volatility=55.0,
        recovery_days=400,
        summary="Oil surged above $120, regimes fell, tourism collapsed, regional instability persisted."
    ),
    HistoricalEvent(
        id="crimea-annexation-2014",
        name="Russia Annexation of Crimea (2014)",
        description="In February-March 2014, Russia invaded and annexed Crimea from Ukraine following the Euromaidan revolution that ousted pro-Russian President Yanukovych. The annexation was condemned internationally and led to Western sanctions against Russia. Russia was expelled from the G8. The conflict in Eastern Ukraine (Donbas) erupted as pro-Russian separatists seized territory. Energy prices initially fell due to global oversupply, but European gas security concerns intensified. NATO increased its presence in Eastern Europe. The annexation marked the first forcible border change in Europe since WWII and fundamentally altered European security architecture.",
        date="2014-03-18",
        event_type="conflict",
        entities=["Russia", "Ukraine", "Crimea", "United States", "European Union", "NATO", "G8", "Donbas"],
        sectors=["Energy", "Defense", "Financials", "Agriculture"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=10.0, volatility=35.0, recovery_days=120),
            MarketOutcome(sector="Defense", impact_pct=12.0, volatility=20.0, recovery_days=60),
            MarketOutcome(sector="Financials", impact_pct=-5.0, volatility=30.0, recovery_days=90),
            MarketOutcome(sector="Agriculture", impact_pct=5.0, volatility=20.0, recovery_days=45),
        ],
        volatility=35.0,
        recovery_days=120,
        summary="Western sanctions imposed, energy security concerns rose, NATO reinforced Eastern Europe."
    ),
    HistoricalEvent(
        id="us-china-trade-war-2018",
        name="US-China Trade War (2018-2019)",
        description="The US-China Trade War began in 2018 when President Trump imposed tariffs on $34 billion of Chinese imports under Section 301 of the Trade Act of 1974. China retaliated with reciprocal tariffs. Over the next two years, tariffs escalated to cover over $550 billion of Chinese goods and $185 billion of US goods. The dispute covered technology transfer, intellectual property, and industrial policy. Supply chains shifted from China to Southeast Asia and Mexico. Stock markets experienced high volatility. The trade war contributed to a slowdown in global economic growth and disrupted global supply chains across technology, manufacturing, and agriculture.",
        date="2018-07-06",
        event_type="economic",
        entities=["United States", "China", "Donald Trump", "Xi Jinping", "WTO", "Asia", "European Union", "Southeast Asia"],
        sectors=["Technology", "Manufacturing", "Agriculture", "Consumer Discretionary", "Semiconductors"],
        outcomes=[
            MarketOutcome(sector="Technology", impact_pct=-15.0, volatility=45.0, recovery_days=300),
            MarketOutcome(sector="Manufacturing", impact_pct=-10.0, volatility=35.0, recovery_days=250),
            MarketOutcome(sector="Agriculture", impact_pct=-20.0, volatility=40.0, recovery_days=200),
            MarketOutcome(sector="Semiconductors", impact_pct=-25.0, volatility=50.0, recovery_days=365),
        ],
        volatility=45.0,
        recovery_days=365,
        summary="Tariffs disrupted global trade, supply chains shifted, markets volatile, tech suffered."
    ),
    HistoricalEvent(
        id="strait-of-hormuz-2019",
        name="Strait of Hormuz Crisis (2019)",
        description="In 2019, a series of escalating incidents in and around the Strait of Hormuz threatened global oil supplies. In May, four commercial ships were sabotaged off Fujairah. In June, the US blamed Iran for attacks on tankers near the Strait. Iran shot down a US drone, almost triggering US retaliation. In September, a major attack on Saudi Aramco's Abqaiq and Khurais facilities temporarily cut 5.7 million barrels per day (5.7% of global supply) — the largest single supply disruption in history. Oil prices spiked 15% in a single day. The US and UK formed a naval coalition to protect shipping lanes. Tensions remained elevated throughout the year.",
        date="2019-06-13",
        event_type="conflict",
        entities=["Iran", "United States", "Saudi Arabia", "Strait of Hormuz", "UK", "UAE", "Saudi Aramco", "IRGC"],
        sectors=["Energy", "Defense", "Shipping", "Insurance"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=15.0, volatility=55.0, recovery_days=60),
            MarketOutcome(sector="Defense", impact_pct=8.0, volatility=25.0, recovery_days=30),
            MarketOutcome(sector="Shipping", impact_pct=-10.0, volatility=45.0, recovery_days=45),
            MarketOutcome(sector="Insurance", impact_pct=12.0, volatility=30.0, recovery_days=60),
        ],
        volatility=55.0,
        recovery_days=60,
        summary="Oil spiked 15% in one day, shipping disrupted, Aramco attack cut 5.7M bpd."
    ),
    HistoricalEvent(
        id="covid-19-pandemic-2020",
        name="COVID-19 Global Pandemic (2020)",
        description="The COVID-19 pandemic, caused by SARS-CoV-2, began in Wuhan, China in late 2019 and became a global pandemic by March 2020. Governments worldwide implemented unprecedented lockdowns, travel bans, and social distancing measures. Global GDP contracted by 3.5% in 2020. Oil prices briefly turned negative for the first time in history, reaching -$37 per barrel. The S&P 500 fell 34% in record time before recovering due to massive stimulus. Central banks cut rates to near zero and implemented quantitative easing. The pandemic accelerated digital transformation, e-commerce, and remote work. Supply chains were severely disrupted globally.",
        date="2020-03-11",
        event_type="disaster",
        entities=["WHO", "China", "United States", "European Union", "UK", "India", "Brazil", "World Bank", "IMF"],
        sectors=["Travel & Hospitality", "Energy", "Technology", "Healthcare", "Consumer Discretionary", "E-commerce"],
        outcomes=[
            MarketOutcome(sector="Travel & Hospitality", impact_pct=-70.0, volatility=85.0, recovery_days=800),
            MarketOutcome(sector="Energy", impact_pct=-55.0, volatility=90.0, recovery_days=500),
            MarketOutcome(sector="Technology", impact_pct=30.0, volatility=45.0, recovery_days=180),
            MarketOutcome(sector="Healthcare", impact_pct=25.0, volatility=35.0, recovery_days=120),
            MarketOutcome(sector="E-commerce", impact_pct=50.0, volatility=30.0, recovery_days=90),
        ],
        volatility=90.0,
        recovery_days=800,
        summary="Markets crashed 34%, oil went negative, tech surged, travel devastated, massive stimulus."
    ),
    HistoricalEvent(
        id="russia-ukraine-war-2022",
        name="Russia-Ukraine War (2022)",
        description="On February 24, 2022, Russia launched a full-scale invasion of Ukraine, the largest conventional military attack in Europe since World War II. The invasion triggered devastating sanctions against Russia, including SWIFT removal, asset freezes, and energy embargoes. Oil surged above $130 per barrel, European gas prices hit record highs (over 10x normal), and wheat prices soared 60%. Global supply chains for energy, food, and industrial metals were severely disrupted. NATO was strengthened with Finland and Sweden joining. Defense spending surged across Europe. Central banks faced a dilemma of high inflation versus slowing growth. The conflict caused over 8 million refugees and devastated Ukraine's infrastructure and economy.",
        date="2022-02-24",
        event_type="conflict",
        entities=["Russia", "Ukraine", "NATO", "European Union", "United States", "Vladimir Putin", "Volodymyr Zelenskyy", "China", "Belarus", "Black Sea"],
        sectors=["Energy", "Defense", "Agriculture", "Technology", "Airlines", "Financials", "Shipping"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=130.0, volatility=80.0, recovery_days=500),
            MarketOutcome(sector="Defense", impact_pct=40.0, volatility=25.0, recovery_days=90),
            MarketOutcome(sector="Agriculture", impact_pct=60.0, volatility=55.0, recovery_days=365),
            MarketOutcome(sector="Technology", impact_pct=-15.0, volatility=40.0, recovery_days=200),
            MarketOutcome(sector="Airlines", impact_pct=-20.0, volatility=50.0, recovery_days=250),
        ],
        volatility=80.0,
        recovery_days=500,
        summary="Oil above $130, gas prices 10x, wheat surged 60%, defense stocks soared, massive sanctions."
    ),
    HistoricalEvent(
        id="taiwan-strait-2022",
        name="Taiwan Strait Tensions (2022)",
        description="Following US House Speaker Nancy Pelosi's visit to Taiwan on August 2-3, 2022, China conducted unprecedented large-scale military exercises around Taiwan, launching ballistic missiles over the island for the first time. China's People's Liberation Army encircled Taiwan with live-fire drills, effectively simulating a blockade. The exercises disrupted major shipping lanes and global semiconductor supply chains, given Taiwan produces over 60% of the world's semiconductors and 90% of advanced chips. The crisis highlighted the risk of a full-scale Taiwan blockade scenario. Global defense stocks, particularly in Japan, South Korea, and the US, rose sharply. Technology companies with Taiwan exposure faced significant risk assessment challenges.",
        date="2022-08-02",
        event_type="conflict",
        entities=["China", "Taiwan", "United States", "Nancy Pelosi", "Japan", "South Korea", "PLA", "TSMC", "Semiconductor Industry", "Pacific"],
        sectors=["Semiconductors", "Technology", "Defense", "Shipping", "Manufacturing"],
        outcomes=[
            MarketOutcome(sector="Semiconductors", impact_pct=-12.0, volatility=60.0, recovery_days=120),
            MarketOutcome(sector="Defense", impact_pct=15.0, volatility=30.0, recovery_days=45),
            MarketOutcome(sector="Shipping", impact_pct=-8.0, volatility=40.0, recovery_days=60),
            MarketOutcome(sector="Technology", impact_pct=-10.0, volatility=45.0, recovery_days=90),
        ],
        volatility=60.0,
        recovery_days=120,
        summary="Semiconductor supply chain fears, defense stocks surged, China encircled Taiwan with drills."
    ),
    HistoricalEvent(
        id="red-sea-shipping-2023",
        name="Red Sea / Bab el-Mandeb Shipping Crisis (2023-2024)",
        description="Beginning in November 2023, Houthi rebels in Yemen launched repeated attacks on commercial shipping in the Red Sea and Bab el-Mandeb strait, a critical chokepoint for global trade. Attacks targeted vessels with suspected Israeli links in solidarity with Palestinians during the Israel-Hamas War. Major shipping companies including Maersk, Hapag-Lloyd, and MSC rerouted vessels around the Cape of Good Hope, adding 10-14 days to transit times and increasing costs by 200-300%. Global shipping rates surged 150%+ on key routes. The crisis disrupted supply chains for oil, LNG, consumer goods, and manufactured products. The US and UK launched Operation Prosperity Guardian and conducted strikes against Houthi targets in Yemen. Insurance premiums for Red Sea transits increased tenfold. The crisis highlighted the vulnerability of global maritime chokepoints.",
        date="2023-11-19",
        event_type="conflict",
        entities=["Yemen", "Houthi Rebels", "Iran", "Israel", "United States", "UK", "Egypt", "Suez Canal", "Red Sea", "Maersk", "MSC"],
        sectors=["Shipping", "Energy", "Insurance", "Retail", "Manufacturing"],
        outcomes=[
            MarketOutcome(sector="Shipping", impact_pct=150.0, volatility=65.0, recovery_days=200),
            MarketOutcome(sector="Energy", impact_pct=12.0, volatility=45.0, recovery_days=120),
            MarketOutcome(sector="Insurance", impact_pct=30.0, volatility=40.0, recovery_days=180),
            MarketOutcome(sector="Retail", impact_pct=-5.0, volatility=25.0, recovery_days=90),
        ],
        volatility=65.0,
        recovery_days=200,
        summary="Shipping costs surged 150%+, Suez Canal bypassed, global supply chains disrupted."
    ),
    HistoricalEvent(
        id="israel-hamas-war-2023",
        name="Israel-Hamas War (2023)",
        description="On October 7, 2023, Hamas launched a coordinated surprise attack on Israel from Gaza, involving thousands of rockets, ground infiltration, and hostage taking. Approximately 1,200 Israelis were killed and 240 taken hostage. Israel responded with massive military operations in Gaza, including sustained aerial bombardment and ground invasion. The conflict led to a severe humanitarian crisis in Gaza. Regional escalation risks included Hezbollah in Lebanon engaging Israel, Houthi attacks in the Red Sea, and Iran-backed militia attacks on US forces in Iraq and Syria. Oil prices initially spiked 6-8% then stabilized as direct supply disruption was limited. Defense stocks rose globally. The conflict reshaped Middle Eastern diplomatic dynamics and threatened normalization efforts between Israel and Saudi Arabia.",
        date="2023-10-07",
        event_type="conflict",
        entities=["Israel", "Hamas", "Gaza", "Iran", "Hezbollah", "Lebanon", "United States", "Egypt", "Saudi Arabia", "IRGC", "Yemen"],
        sectors=["Energy", "Defense", "Technology", "Travel & Hospitality"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=8.0, volatility=50.0, recovery_days=90),
            MarketOutcome(sector="Defense", impact_pct=12.0, volatility=25.0, recovery_days=45),
            MarketOutcome(sector="Technology", impact_pct=-3.0, volatility=30.0, recovery_days=60),
            MarketOutcome(sector="Travel & Hospitality", impact_pct=-8.0, volatility=35.0, recovery_days=120),
        ],
        volatility=50.0,
        recovery_days=120,
        summary="Oil spiked 8%, defense stocks rose, regional escalation risk remained elevated."
    ),
    HistoricalEvent(
        id="colonial-pipeline-cyber-2021",
        name="Colonial Pipeline Cyberattack (2021)",
        description="On May 7, 2021, the Colonial Pipeline, the largest fuel pipeline in the United States carrying 45% of the East Coast's fuel supply, was hit by a ransomware attack attributed to the DarkSide cybercriminal group. The pipeline was shut down for six days, causing widespread fuel shortages, panic buying, and gas lines across the Southeastern US. Average gas prices rose above $3 per gallon for the first time since 2014. The attack highlighted critical infrastructure vulnerabilities and led to a surge in cybersecurity spending and regulatory action. The Biden administration issued an executive order on improving cybersecurity. The Colonial Pipeline paid a $4.4 million ransom, much of which was later recovered by the DOJ.",
        date="2021-05-07",
        event_type="cyber",
        entities=["United States", "Colonial Pipeline", "DarkSide", "DOJ", "FBI", "DHS", "CISA"],
        sectors=["Energy", "Technology", "Cybersecurity", "Transportation"],
        outcomes=[
            MarketOutcome(sector="Cybersecurity", impact_pct=15.0, volatility=25.0, recovery_days=60),
            MarketOutcome(sector="Energy", impact_pct=-3.0, volatility=30.0, recovery_days=15),
            MarketOutcome(sector="Technology", impact_pct=3.0, volatility=20.0, recovery_days=30),
        ],
        volatility=30.0,
        recovery_days=15,
        summary="Fuel shortages hit US East Coast, gas prices surged, cybersecurity spending jumped."
    ),
    HistoricalEvent(
        id="afghanistan-withdrawal-2021",
        name="US Afghanistan Withdrawal / Taliban Takeover (2021)",
        description="In August 2021, the United States completed its withdrawal from Afghanistan after 20 years of war, the longest in US history. The Afghan government collapsed faster than anticipated, and the Taliban retook control of the country in a matter of days. The chaotic evacuation at Kabul airport included over 122,000 people airlifted out, ending with a deadly ISIS-K suicide bombing that killed 13 US service members and 170 Afghans. The withdrawal raised questions about US reliability as an ally and emboldened adversaries. Defense stocks initially dipped but recovered. Geopolitical analysts compared the withdrawal to the Fall of Saigon in 1975. China and Russia moved to fill the power vacuum in the region.",
        date="2021-08-30",
        event_type="political",
        entities=["United States", "Afghanistan", "Taliban", "ISIS-K", "China", "Russia", "Pakistan", "NATO"],
        sectors=["Defense", "Technology", "Airlines"],
        outcomes=[
            MarketOutcome(sector="Defense", impact_pct=-5.0, volatility=20.0, recovery_days=30),
            MarketOutcome(sector="Airlines", impact_pct=-2.0, volatility=15.0, recovery_days=15),
        ],
        volatility=20.0,
        recovery_days=30,
        summary="Taliban retook Afghanistan, chaotic US withdrawal, credibility concerns, defense stocks dipped."
    ),
    HistoricalEvent(
        id="saudi-oil-attack-2019",
        name="Saudi Aramco Abqaiq-Khurais Attack (2019)",
        description="On September 14, 2019, a coordinated drone and missile attack struck Saudi Aramco's Abqaiq oil processing facility and the Khurais oil field, temporarily cutting 5.7 million barrels per day of production — approximately 5.7% of the global oil supply. The attack was claimed by Houthi rebels in Yemen but widely attributed to Iran. It was the largest single disruption to global oil supplies in history. Oil prices jumped 15% in a single day, the largest percentage gain since the Gulf War. Saudi Arabia restored production faster than expected, and prices stabilized within weeks. The attack revealed the vulnerability of critical energy infrastructure to precision drone strikes and missile attacks. Global energy security concerns escalated significantly.",
        date="2019-09-14",
        event_type="conflict",
        entities=["Saudi Arabia", "Iran", "Houthi Rebels", "Saudi Aramco", "United States", "Yemen", "OPEC"],
        sectors=["Energy", "Defense", "Insurance"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=15.0, volatility=55.0, recovery_days=45),
            MarketOutcome(sector="Defense", impact_pct=5.0, volatility=20.0, recovery_days=25),
            MarketOutcome(sector="Insurance", impact_pct=8.0, volatility=25.0, recovery_days=30),
        ],
        volatility=55.0,
        recovery_days=45,
        summary="Biggest oil supply disruption in history, 15% single-day price spike, energy vulnerability exposed."
    ),
    HistoricalEvent(
        id="opec-price-war-2020",
        name="OPEC+ Russia Price War (2020)",
        description="In March 2020, Saudi Arabia launched an oil price war with Russia after OPEC+ negotiations collapsed. Saudi Arabia slashed official selling prices and announced plans to increase production to 12.3 million barrels per day, flooding the market. The price war coincided with the COVID-19 pandemic's destruction of oil demand, creating a perfect storm. Oil prices collapsed to levels not seen in decades. The crisis ultimately forced a historic OPEC+ production cut of 9.7 million barrels per day in April 2020. The price war caused severe financial stress on US shale producers, many of which filed for bankruptcy. It reshaped the global energy industry and accelerated the push for energy diversification in major consuming nations.",
        date="2020-03-08",
        event_type="economic",
        entities=["Saudi Arabia", "Russia", "OPEC", "United States", "Shale Producers", "Vladimir Putin", "Mohammed bin Salman"],
        sectors=["Energy", "Financials", "Technology"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=-65.0, volatility=90.0, recovery_days=400),
            MarketOutcome(sector="Financials", impact_pct=-15.0, volatility=50.0, recovery_days=200),
        ],
        volatility=90.0,
        recovery_days=400,
        summary="Oil crashed, Saudi-Russia price war, US shale bankruptcies, historic OPEC+ cuts."
    ),
    HistoricalEvent(
        id="north-korea-2017",
        name="North Korea Missile Crisis (2017)",
        description="In 2017, North Korea conducted a series of increasingly provocative missile tests, including intercontinental ballistic missiles (ICBMs) capable of reaching the US mainland and its sixth and most powerful nuclear test. Kim Jong Un and Donald Trump exchanged threats of 'fire and fury' and 'totally destroying' North Korea. Global markets experienced periodic volatility spikes on each missile test. Defense stocks in Japan, South Korea, and the US benefited. The crisis led to tightened UN sanctions and increased US military presence in the region. Diplomatic efforts eventually led to the 2018 Singapore Summit between Trump and Kim. The crisis demonstrated the market impact of isolated geopolitical events, typically causing short-term volatility spikes rather than sustained moves.",
        date="2017-09-03",
        event_type="conflict",
        entities=["North Korea", "South Korea", "United States", "Japan", "Kim Jong Un", "Donald Trump", "UN", "ICBM"],
        sectors=["Defense", "Technology", "Financials"],
        outcomes=[
            MarketOutcome(sector="Defense", impact_pct=10.0, volatility=25.0, recovery_days=30),
            MarketOutcome(sector="Technology", impact_pct=-3.0, volatility=35.0, recovery_days=15),
            MarketOutcome(sector="Financials", impact_pct=-2.0, volatility=30.0, recovery_days=10),
        ],
        volatility=35.0,
        recovery_days=30,
        summary="Periodic volatility spikes, defense stocks rose, ICBM and H-bomb tests, fire and fury rhetoric."
    ),
    HistoricalEvent(
        id="soleimani-assassination-2020",
        name="US Killing of Qasem Soleimani (2020)",
        description="On January 3, 2020, the United States conducted a drone strike at Baghdad International Airport that killed Iranian Major General Qasem Soleimani, head of the Islamic Revolutionary Guard Corps' Quds Force, and Iraqi militia commander Abu Mahdi al-Muhandis. Iran retaliated days later with ballistic missile strikes on US bases in Iraq, causing traumatic brain injuries to over 100 US service members. Iran also accidentally shot down Ukraine International Airlines Flight 752, killing all 176 onboard. Oil prices spiked 4% immediately. Global defense stocks rose. Markets experienced a sharp but short-lived risk-off move. The strike represented a major escalation in US-Iran tensions and raised fears of a full-scale war in the Middle East.",
        date="2020-01-03",
        event_type="conflict",
        entities=["Iran", "United States", "Iraq", "Qasem Soleimani", "IRGC", "Quds Force", "Baghdad", "Ukraine International Airlines"],
        sectors=["Energy", "Defense", "Airlines", "Financials"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=8.0, volatility=45.0, recovery_days=30),
            MarketOutcome(sector="Defense", impact_pct=12.0, volatility=25.0, recovery_days=20),
            MarketOutcome(sector="Airlines", impact_pct=-5.0, volatility=35.0, recovery_days=25),
            MarketOutcome(sector="Financials", impact_pct=-3.0, volatility=30.0, recovery_days=15),
        ],
        volatility=45.0,
        recovery_days=30,
        summary="Oil spiked 4%, defense stocks rallied, Iran retaliated with missile strikes, short-term volatility spike."
    ),
    HistoricalEvent(
        id="iran-nuclear-deal-2015",
        name="Iran Nuclear Deal / JCPOA (2015)",
        description="On July 14, 2015, Iran and the P5+1 (US, UK, France, Russia, China, Germany) reached the Joint Comprehensive Plan of Action (JCPOA), limiting Iran's nuclear program in exchange for sanctions relief. The deal allowed Iran to resume oil exports, increasing global supply by approximately 1 million barrels per day. Oil prices, already in a downtrend, fell further. European and Asian companies rushed to re-enter the Iranian market. The deal was hailed as a landmark diplomatic achievement but criticized by Israel, Saudi Arabia, and US Republicans. Sanctions relief unlocked billions in frozen Iranian assets. The deal demonstrated how diplomatic resolution can rapidly alter energy market dynamics.",
        date="2015-07-14",
        event_type="political",
        entities=["Iran", "United States", "UK", "France", "Russia", "China", "Germany", "P5+1", "IAEA", "EU", "Israel", "Saudi Arabia"],
        sectors=["Energy", "Financials", "Manufacturing", "Airlines"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=-10.0, volatility=30.0, recovery_days=90),
            MarketOutcome(sector="Financials", impact_pct=5.0, volatility=15.0, recovery_days=30),
            MarketOutcome(sector="Manufacturing", impact_pct=3.0, volatility=10.0, recovery_days=20),
        ],
        volatility=30.0,
        recovery_days=90,
        summary="Iran returned to oil markets, prices fell 10%, sanctions relief unlocked trade, diplomatic milestone."
    ),
    HistoricalEvent(
        id="us-iran-shadow-war-2021",
        name="US-Iran Shadow War & Nuclear Escalation (2021-2023)",
        description="Following the US withdrawal from the JCPOA in 2018 and maximum pressure campaign, Iran accelerated its nuclear program, enriching uranium to 60% purity (near weapons-grade) by 2023. A shadow war unfolded through cyber attacks, drone strikes, attacks on shipping, and proxy forces across the Middle East. Iran supplied drones to Russia for use in Ukraine. Attacks on US bases in Syria and Iraq increased. The US and Israel conducted covert operations against Iran's nuclear and military infrastructure. Tanker seizures in the Persian Gulf became frequent. European-mediated diplomatic efforts to revive the nuclear deal stalled repeatedly. The situation kept a constant risk premium in oil markets of $5-10 per barrel.",
        date="2021-04-11",
        event_type="conflict",
        entities=["Iran", "United States", "Israel", "IAEA", "EU", "Russia", "Saudi Arabia", "IRGC", "Persian Gulf", "Syria", "Iraq", "Yemen"],
        sectors=["Energy", "Defense", "Shipping", "Technology"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=10.0, volatility=40.0, recovery_days=200),
            MarketOutcome(sector="Defense", impact_pct=8.0, volatility=20.0, recovery_days=60),
            MarketOutcome(sector="Shipping", impact_pct=-5.0, volatility=35.0, recovery_days=120),
            MarketOutcome(sector="Technology", impact_pct=-2.0, volatility=25.0, recovery_days=45),
        ],
        volatility=40.0,
        recovery_days=200,
        summary="Iran enriched uranium to 60%, shadow war escalated, constant $5-10 oil risk premium, nuclear talks stalled."
    ),
    HistoricalEvent(
        id="sudan-conflict-2023",
        name="Sudan Civil War (2023)",
        description="In April 2023, a major armed conflict broke out in Sudan between the Sudanese Armed Forces (SAF) and the paramilitary Rapid Support Forces (RSF). The conflict caused a severe humanitarian crisis with over 8 million displaced. Gold production, a key Sudanese export, was disrupted. Global commodities markets saw minor supply effects. The conflict highlighted the risks of investing in fragile states and caused regional instability in the Horn of Africa. Red Sea shipping security concerns rose. Oil prices experienced marginal increases due to proximity to key shipping routes.",
        date="2023-04-15",
        event_type="conflict",
        entities=["Sudan", "SAF", "RSF", "Gold", "Horn of Africa", "Red Sea", "Africa"],
        sectors=["Energy", "Gold & Precious Metals", "Shipping"],
        outcomes=[
            MarketOutcome(sector="Gold & Precious Metals", impact_pct=3.0, volatility=15.0, recovery_days=30),
            MarketOutcome(sector="Energy", impact_pct=2.0, volatility=10.0, recovery_days=15),
            MarketOutcome(sector="Shipping", impact_pct=4.0, volatility=20.0, recovery_days=45),
        ],
        volatility=15.0,
        recovery_days=45,
        summary="Humanitarian crisis in Sudan, gold production disrupted, minor impact on global markets."
    ),
    HistoricalEvent(
        id="uk-gas-crisis-2021",
        name="European Energy Crisis (2021-2022)",
        description="Beginning in late 2021, Europe faced a severe energy crisis characterized by record-high gas and electricity prices. Natural gas prices surged over 1000% from mid-2021 peaks to record highs in 2022. Contributing factors included low storage levels, high Asian demand for LNG, reduced Russian gas flows, maintenance outages at nuclear plants in France, and low renewable output. The crisis was exacerbated by the Russia-Ukraine war in February 2022. European governments implemented emergency measures, price caps, and subsidies totaling hundreds of billions of euros. The crisis accelerated Europe's shift to renewable energy and LNG diversification. Industrial production in energy-intensive sectors (chemicals, metals, fertilizers) was significantly reduced.",
        date="2021-10-01",
        event_type="economic",
        entities=["European Union", "Russia", "Germany", "France", "UK", "Norway", "Qatar", "United States", "LNG", "Gazprom"],
        sectors=["Energy", "Manufacturing", "Chemicals", "Utilities", "Agriculture"],
        outcomes=[
            MarketOutcome(sector="Energy", impact_pct=200.0, volatility=85.0, recovery_days=600),
            MarketOutcome(sector="Manufacturing", impact_pct=-15.0, volatility=45.0, recovery_days=400),
            MarketOutcome(sector="Utilities", impact_pct=30.0, volatility=50.0, recovery_days=300),
            MarketOutcome(sector="Agriculture", impact_pct=-10.0, volatility=35.0, recovery_days=200),
        ],
        volatility=85.0,
        recovery_days=600,
        summary="Gas prices surged 1000%+, European industry crippled, massive government intervention, energy transition accelerated."
    ),
]


def seed_events():
    return HISTORICAL_EVENTS
