"""Static data matching the frontend's countries.ts and relations.ts in Python."""

COUNTRY_COORDS = {
    "US": (37.09, -95.71), "CA": (56.13, -106.35), "BR": (-14.24, -51.93),
    "MX": (23.63, -102.55), "AR": (-38.42, -63.62), "CL": (-35.68, -71.54),
    "CO": (4.57, -74.30), "GB": (55.38, -3.44), "DE": (51.17, 10.45),
    "FR": (46.60, 1.89), "CH": (46.82, 8.23), "NL": (52.13, 5.29),
    "SE": (60.13, 18.64), "DK": (56.26, 9.50), "NO": (60.47, 8.47),
    "IT": (41.87, 12.57), "ES": (40.46, -3.75), "IE": (53.41, -8.24),
    "BE": (50.85, 4.35), "PT": (39.40, -8.22), "AT": (47.52, 14.55),
    "FI": (61.92, 25.75), "GR": (39.07, 21.82), "PL": (51.92, 19.15),
    "RU": (61.52, 105.32), "TR": (38.96, 35.24), "JP": (36.20, 138.25),
    "CN": (35.86, 104.19), "HK": (22.32, 114.17), "KR": (35.91, 127.77),
    "IN": (20.59, 78.96), "AU": (-25.27, 133.77), "SG": (1.35, 103.82),
    "TW": (23.70, 120.96), "MY": (4.21, 101.98), "ID": (-0.79, 113.92),
    "TH": (15.87, 100.99), "PH": (12.88, 121.77), "VN": (14.06, 108.28),
    "NZ": (-40.90, 174.89), "AE": (23.42, 53.85), "SA": (23.89, 45.08),
    "QA": (25.35, 51.18), "KW": (29.31, 47.48), "IL": (31.05, 34.85),
    "ZA": (-30.56, 22.94), "NG": (9.08, 8.68), "KE": (-0.02, 37.91),
    "EG": (26.82, 30.80), "MA": (31.79, -7.09), "MU": (-20.35, 57.55),
    "PK": (30.38, 69.35), "IR": (32.43, 53.69),
}

COUNTRIES = [
    {"code": "US", "name": "United States", "region": "Americas", "stockExchange": "NYSE / NASDAQ", "currency": "USD", "currencySymbol": "$", "marketCap": "$50.8T", "tradingHours": "09:30-16:00 ET", "tickers": ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "JPM", "V", "NVDA", "META"], "lat": 37.09, "lng": -95.71, "commodities": ["Oil", "Natural Gas", "Corn", "Soybeans", "Wheat", "Copper", "Gold", "LNG", "Semiconductors", "Automobiles", "Aerospace"], "ports": ["Port of Los Angeles", "Port of New York & New Jersey", "Port of Houston", "Port of Long Beach", "Port of Savannah"]},
    {"code": "CA", "name": "Canada", "region": "Americas", "stockExchange": "TSX", "currency": "CAD", "currencySymbol": "C$", "marketCap": "$3.2T", "tradingHours": "09:30-16:00 ET", "tickers": ["SHOP", "RY", "TD", "ENB", "CNQ", "BMO", "BNS", "SU", "TRP", "CM"], "lat": 56.13, "lng": -106.35, "commodities": ["Oil", "Natural Gas", "Gold", "Potash", "Uranium", "Timber", "Wheat", "Nickel"], "ports": ["Port of Vancouver", "Port of Montreal", "Port of Prince Rupert"]},
    {"code": "BR", "name": "Brazil", "region": "Americas", "stockExchange": "B3", "currency": "BRL", "currencySymbol": "R$", "marketCap": "$1.1T", "tradingHours": "10:00-17:00 BRT", "tickers": ["PETR4", "VALE3", "ITUB4", "ABEV3", "WEGE3", "SUZB3", "BBAS3"], "lat": -14.24, "lng": -51.93, "commodities": ["Iron Ore", "Coffee", "Soybeans", "Sugar", "Beef", "Oil", "Gold", "Orange Juice"], "ports": ["Port of Santos", "Port of Rio de Janeiro", "Port of Paranaguá"]},
    {"code": "MX", "name": "Mexico", "region": "Americas", "stockExchange": "BMV", "currency": "MXN", "currencySymbol": "Mex$", "marketCap": "$450B", "tradingHours": "08:30-15:00 CST", "tickers": ["AMXL", "FEMSA", "WALMEX", "GFNORTE", "GMEXICO", "CEMEX"], "lat": 23.63, "lng": -102.55, "commodities": ["Oil", "Silver", "Gold", "Avocados", "Automobiles", "Copper", "Electronics"], "ports": ["Port of Manzanillo", "Port of Veracruz", "Port of Altamira"]},
    {"code": "AR", "name": "Argentina", "region": "Americas", "stockExchange": "BCBA", "currency": "ARS", "currencySymbol": "AR$", "marketCap": "$85B", "tradingHours": "11:00-17:00 ART", "tickers": ["GGAL", "YPF", "PAMP", "CEPU", "TECO2"], "lat": -38.42, "lng": -63.62, "commodities": ["Soybeans", "Corn", "Wheat", "Beef", "Wine", "Lithium", "Natural Gas"], "ports": ["Port of Buenos Aires", "Port of Rosario"]},
    {"code": "CL", "name": "Chile", "region": "Americas", "stockExchange": "BCS", "currency": "CLP", "currencySymbol": "CLP$", "marketCap": "$210B", "tickers": ["COPEC", "BSANTANDER", "CMPC", "ENELAM", "FALABELLA"], "lat": -35.68, "lng": -71.54, "commodities": ["Copper", "Lithium", "Gold", "Silver", "Wine", "Salmon", "Fruit"], "ports": ["Port of Valparaiso", "Port of San Antonio"]},
    {"code": "CO", "name": "Colombia", "region": "Americas", "stockExchange": "BVC", "currency": "COP", "currencySymbol": "COL$", "marketCap": "$140B", "tickers": ["ECOPETROL", "GRUPOSURA", "BCOLOMBIA", "NUTRESA", "ISA"], "lat": 4.57, "lng": -74.30, "commodities": ["Oil", "Coffee", "Gold", "Coal", "Bananas", "Flowers"], "ports": ["Port of Cartagena", "Port of Buenaventura"]},
    {"code": "GB", "name": "United Kingdom", "region": "Europe", "stockExchange": "LSE", "currency": "GBP", "currencySymbol": "£", "marketCap": "$3.4T", "tradingHours": "08:00-16:30 GMT", "tickers": ["HSBA", "ULVR", "SHEL", "BP", "GSK", "DGE", "RIO", "GLEN", "LLOY"], "lat": 55.38, "lng": -3.44, "commodities": ["Oil", "Natural Gas", "Gold", "Pharmaceuticals", "Financial Services", "Aerospace"], "ports": ["Port of Felixstowe", "Port of Southampton", "Port of London"]},
    {"code": "DE", "name": "Germany", "region": "Europe", "stockExchange": "FWB (Frankfurt)", "currency": "EUR", "currencySymbol": "€", "marketCap": "$2.2T", "tradingHours": "08:00-20:00 CET", "tickers": ["SAP", "ALV", "DBK", "VOW3", "BAYN", "BMW", "ADS", "MRK", "LIN"], "lat": 51.17, "lng": 10.45, "commodities": ["Automobiles", "Chemicals", "Steel", "Machinery", "Pharmaceuticals", "Electronics"], "ports": ["Port of Hamburg", "Port of Bremen", "Port of Wilhelmshaven"]},
    {"code": "FR", "name": "France", "region": "Europe", "stockExchange": "Euronext Paris", "currency": "EUR", "currencySymbol": "€", "marketCap": "$2.8T", "tradingHours": "09:00-17:30 CET", "tickers": ["MC", "OR", "TTE", "SAN", "AIR", "BNP", "SU", "KER"], "lat": 46.60, "lng": 1.89, "commodities": ["Wine", "Aerospace", "Luxury Goods", "Pharmaceuticals", "Wheat", "Dairy", "Nuclear Energy"], "ports": ["Port of Marseille", "Port of Le Havre", "Port of Dunkerque"]},
    {"code": "CH", "name": "Switzerland", "region": "Europe", "stockExchange": "SIX Swiss", "currency": "CHF", "currencySymbol": "CHF", "marketCap": "$1.7T", "tradingHours": "09:00-17:30 CET", "tickers": ["NOVN", "ROG", "NESN", "UBSG", "ABBN", "CFR", "ZURN"], "lat": 46.82, "lng": 8.23, "commodities": ["Gold", "Pharmaceuticals", "Financial Services", "Machinery", "Chocolate", "Watches"], "ports": ["Port of Basel (Rhine)"]},
    {"code": "NL", "name": "Netherlands", "region": "Europe", "stockExchange": "Euronext Amsterdam", "currency": "EUR", "currencySymbol": "€", "marketCap": "$900B", "tickers": ["ASML", "UNA", "INGA", "AD", "KPN", "AKZA", "HEIA"], "lat": 52.13, "lng": 5.29, "commodities": ["Natural Gas", "Chemicals", "Electronics", "Flowers", "Dairy", "Semiconductors"], "ports": ["Port of Rotterdam", "Port of Amsterdam"]},
    {"code": "SE", "name": "Sweden", "region": "Europe", "stockExchange": "OMX Nordic Stockholm", "currency": "SEK", "currencySymbol": "kr", "marketCap": "$820B", "tickers": ["ERIC", "SEB", "VOLV", "ABB", "ATCO", "SAND", "SHB"], "lat": 60.13, "lng": 18.64, "commodities": ["Iron Ore", "Timber", "Steel", "Machinery", "Automobiles", "Telecom"], "ports": ["Port of Gothenburg", "Port of Stockholm"]},
    {"code": "DK", "name": "Denmark", "region": "Europe", "stockExchange": "OMX Nordic Copenhagen", "currency": "DKK", "currencySymbol": "kr", "tickers": ["NOVO", "DSV", "NZYM", "MAERSK", "CARL", "VWS", "GN"], "lat": 56.26, "lng": 9.50, "commodities": ["Pharmaceuticals", "Wind Energy", "Dairy", "Pork", "Furniture"], "ports": ["Port of Copenhagen", "Port of Aarhus"]},
    {"code": "NO", "name": "Norway", "region": "Europe", "stockExchange": "Oslo Børs", "currency": "NOK", "currencySymbol": "kr", "tickers": ["EQUINOR", "DNB", "ORK", "NHY", "YAR", "MOWI", "SUBC"], "lat": 60.47, "lng": 8.47, "commodities": ["Oil", "Natural Gas", "Fish", "Aluminum", "Fertilizer", "Timber"], "ports": ["Port of Oslo", "Port of Bergen"]},
    {"code": "IT", "name": "Italy", "region": "Europe", "stockExchange": "Borsa Italiana", "currency": "EUR", "currencySymbol": "€", "marketCap": "$700B", "tickers": ["ENI", "ISP", "ENEL", "UCG", "LDO", "PRY", "RACE"], "lat": 41.87, "lng": 12.57, "commodities": ["Wine", "Olive Oil", "Fashion", "Automobiles", "Machinery", "Steel", "Fruit"], "ports": ["Port of Genoa", "Port of Trieste", "Port of Naples"]},
    {"code": "ES", "name": "Spain", "region": "Europe", "stockExchange": "BME (Madrid)", "currency": "EUR", "currencySymbol": "€", "marketCap": "$650B", "tickers": ["SAN", "BBVA", "TEF", "IBE", "REP", "FER", "AENA"], "lat": 40.46, "lng": -3.75, "commodities": ["Olive Oil", "Wine", "Fruit", "Automobiles", "Renewable Energy", "Tourism"], "ports": ["Port of Algeciras", "Port of Barcelona", "Port of Valencia"]},
    {"code": "IE", "name": "Ireland", "region": "Europe", "stockExchange": "Euronext Dublin", "currency": "EUR", "currencySymbol": "€", "tickers": ["CRH", "KER", "RYAI", "DCC"], "lat": 53.41, "lng": -8.24, "commodities": ["Pharmaceuticals", "Dairy", "Beef", "Tech Services", "Whiskey"], "ports": ["Port of Dublin", "Port of Cork"]},
    {"code": "BE", "name": "Belgium", "region": "Europe", "stockExchange": "Euronext Brussels", "currency": "EUR", "currencySymbol": "€", "tickers": ["ABI", "UCB", "KBC", "SOLB"], "lat": 50.85, "lng": 4.35, "commodities": ["Chemicals", "Pharmaceuticals", "Diamonds", "Chocolate", "Steel"], "ports": ["Port of Antwerp", "Port of Zeebrugge"]},
    {"code": "PT", "name": "Portugal", "region": "Europe", "stockExchange": "Euronext Lisbon", "currency": "EUR", "currencySymbol": "€", "tickers": ["EDP", "BCP", "GALP", "RENE"], "lat": 39.40, "lng": -8.22, "commodities": ["Wine", "Cork", "Olive Oil", "Fish", "Renewable Energy"], "ports": ["Port of Lisbon", "Port of Sines"]},
    {"code": "AT", "name": "Austria", "region": "Europe", "stockExchange": "Wiener Börse", "currency": "EUR", "currencySymbol": "€", "tickers": ["EBS", "OMV", "RBI", "VOE"], "lat": 47.52, "lng": 14.55, "commodities": ["Steel", "Machinery", "Timber", "Chemicals", "Tourism"], "ports": ["Port of Vienna (Danube)"]},
    {"code": "FI", "name": "Finland", "region": "Europe", "stockExchange": "OMX Nordic Helsinki", "currency": "EUR", "currencySymbol": "€", "tickers": ["NOKIA", "NESTE", "KNEBV", "SAMPO"], "lat": 61.92, "lng": 25.75, "commodities": ["Timber", "Paper", "Tech", "Steel", "Chemicals"], "ports": ["Port of Helsinki", "Port of HaminaKotka"]},
    {"code": "GR", "name": "Greece", "region": "Europe", "stockExchange": "ATHEX", "currency": "EUR", "currencySymbol": "€", "marketCap": "$65B", "tickers": ["ALPHA", "EUROB", "PPC", "OPAP"], "lat": 39.07, "lng": 21.82, "commodities": ["Olive Oil", "Shipping", "Fruit", "Wine", "Tobacco"], "ports": ["Port of Piraeus", "Port of Thessaloniki"]},
    {"code": "PL", "name": "Poland", "region": "Europe", "stockExchange": "GPW (Warsaw)", "currency": "PLN", "currencySymbol": "zł", "marketCap": "$160B", "tickers": ["PKN", "PKOBP", "PZU", "CDR"], "lat": 51.92, "lng": 19.15, "commodities": ["Coal", "Steel", "Chemicals", "Food Processing", "Automotive Parts"], "ports": ["Port of Gdansk", "Port of Gdynia"]},
    {"code": "RU", "name": "Russia", "region": "Europe", "stockExchange": "MOEX", "currency": "RUB", "currencySymbol": "₽", "tickers": ["SBER", "GAZP", "LKOH", "ROSN"], "lat": 61.52, "lng": 105.32, "commodities": ["Oil", "Natural Gas", "Coal", "Gold", "Nickel", "Diamonds", "Wheat", "Timber", "Aluminum", "Steel"], "ports": ["Port of Novorossiysk", "Port of Saint Petersburg", "Port of Vladivostok"]},
    {"code": "TR", "name": "Turkey", "region": "Europe", "stockExchange": "BIST", "currency": "TRY", "currencySymbol": "₺", "marketCap": "$180B", "tickers": ["THYAO", "GARAN", "KOCHOL", "EREGL"], "lat": 38.96, "lng": 35.24, "commodities": ["Textiles", "Automotive", "Steel", "Fruit", "Ceramics", "Chemicals"], "ports": ["Port of Istanbul", "Port of Izmir", "Port of Mersin"]},
    {"code": "JP", "name": "Japan", "region": "Asia Pacific", "stockExchange": "TSE (Tokyo)", "currency": "JPY", "currencySymbol": "¥", "marketCap": "$6.7T", "tradingHours": "09:00-15:00 JST", "tickers": ["TM", "SONY", "MUFG", "SMFG", "NTT", "KDDI"], "lat": 36.20, "lng": 138.25, "commodities": ["Automobiles", "Electronics", "Steel", "Chemicals", "Semiconductors", "Robotics"], "ports": ["Port of Tokyo", "Port of Yokohama", "Port of Osaka", "Port of Nagoya"]},
    {"code": "CN", "name": "China", "region": "Asia Pacific", "stockExchange": "SSE / HKEX", "currency": "CNY", "currencySymbol": "¥", "marketCap": "$8.2T", "tradingHours": "09:30-15:00 CST", "tickers": ["BABA", "TCEHY", "JD", "BIDU", "NIO", "PDD"], "lat": 35.86, "lng": 104.19, "commodities": ["Rare Earth", "Steel", "Electronics", "Textiles", "Coal", "Solar Panels", "Lithium", "Rare Earth Minerals", "Aluminum"], "ports": ["Port of Shanghai", "Port of Shenzhen", "Port of Ningbo-Zhoushan", "Port of Guangzhou", "Port of Qingdao"]},
    {"code": "HK", "name": "Hong Kong", "region": "Asia Pacific", "stockExchange": "HKEX", "currency": "HKD", "currencySymbol": "HK$", "marketCap": "$4.1T", "tickers": ["TCEHY", "BABA", "HSB", "1299"], "lat": 22.32, "lng": 114.17, "commodities": ["Financial Services", "Logistics", "Electronics", "Jewelry"], "ports": ["Port of Hong Kong"]},
    {"code": "KR", "name": "South Korea", "region": "Asia Pacific", "stockExchange": "KRX", "currency": "KRW", "currencySymbol": "₩", "marketCap": "$1.8T", "tradingHours": "09:00-15:30 KST", "tickers": ["SAMSUNG", "HYMC", "SKHY", "POSCO", "KB", "KAKAO", "NAVER"], "lat": 35.91, "lng": 127.77, "commodities": ["Semiconductors", "Automobiles", "Steel", "Shipbuilding", "Electronics", "Petrochemicals"], "ports": ["Port of Busan", "Port of Incheon", "Port of Ulsan"]},
    {"code": "IN", "name": "India", "region": "Asia Pacific", "stockExchange": "BSE / NSE", "currency": "INR", "currencySymbol": "₹", "marketCap": "$3.5T", "tradingHours": "09:15-15:30 IST", "tickers": ["RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK", "SBIN", "BHARTIARTL"], "lat": 20.59, "lng": 78.96, "commodities": ["Rice", "Wheat", "Cotton", "Tea", "Steel", "Pharmaceuticals", "IT Services", "Diamonds"], "ports": ["Port of Mumbai", "Port of Chennai", "Port of Mundra", "Port of Kolkata"]},
    {"code": "AU", "name": "Australia", "region": "Asia Pacific", "stockExchange": "ASX", "currency": "AUD", "currencySymbol": "A$", "marketCap": "$1.8T", "tradingHours": "10:00-16:00 AEDT", "tickers": ["BHP", "CBA", "CSL", "NAB", "WBC", "ANZ", "WOW", "TLS", "RIO"], "lat": -25.27, "lng": 133.77, "commodities": ["Iron Ore", "Coal", "Gold", "LNG", "Wheat", "Beef", "Wine", "Lithium", "Copper", "Nickel"], "ports": ["Port of Port Hedland", "Port of Sydney", "Port of Melbourne", "Port of Brisbane"]},
    {"code": "SG", "name": "Singapore", "region": "Asia Pacific", "stockExchange": "SGX", "currency": "SGD", "currencySymbol": "S$", "marketCap": "$600B", "tradingHours": "09:00-17:00 SGT", "tickers": ["DBS", "OCBC", "UOB", "SBUX", "WIL", "KEP"], "lat": 1.35, "lng": 103.82, "commodities": ["Electronics", "Chemicals", "Pharmaceuticals", "Financial Services", "Oil Refining"], "ports": ["Port of Singapore"]},
    {"code": "TW", "name": "Taiwan", "region": "Asia Pacific", "stockExchange": "TWSE", "currency": "TWD", "currencySymbol": "NT$", "marketCap": "$1.2T", "tickers": ["TSMC", "FOXCONN", "MTK", "HTC"], "lat": 23.70, "lng": 120.96, "commodities": ["Semiconductors", "Electronics", "Machinery", "Steel", "Petrochemicals"], "ports": ["Port of Kaohsiung", "Port of Taipei"]},
    {"code": "MY", "name": "Malaysia", "region": "Asia Pacific", "stockExchange": "Bursa Malaysia", "currency": "MYR", "currencySymbol": "RM", "marketCap": "$350B", "tickers": ["MAYBANK", "CIMB", "PUBLIC", "TENAGA"], "lat": 4.21, "lng": 101.98, "commodities": ["Palm Oil", "Rubber", "Oil", "Natural Gas", "Electronics", "Timber"], "ports": ["Port of Klang", "Port of Tanjung Pelepas"]},
    {"code": "ID", "name": "Indonesia", "region": "Asia Pacific", "stockExchange": "IDX", "currency": "IDR", "currencySymbol": "Rp", "marketCap": "$500B", "tickers": ["BBCA", "BBRI", "TLKM", "ASII"], "lat": -0.79, "lng": 113.92, "commodities": ["Palm Oil", "Coal", "Nickel", "Rubber", "Coffee", "Oil", "Natural Gas", "Tin"], "ports": ["Port of Tanjung Priok", "Port of Surabaya", "Port of Belawan"]},
    {"code": "TH", "name": "Thailand", "region": "Asia Pacific", "stockExchange": "SET", "currency": "THB", "currencySymbol": "฿", "marketCap": "$450B", "tickers": ["CPALL", "PTT", "AOT", "ADVANC"], "lat": 15.87, "lng": 100.99, "commodities": ["Rice", "Rubber", "Electronics", "Automotive", "Sugar", "Seafood", "Tourism"], "ports": ["Port of Bangkok", "Port of Laem Chabang"]},
    {"code": "PH", "name": "Philippines", "region": "Asia Pacific", "stockExchange": "PSE", "currency": "PHP", "currencySymbol": "₱", "tickers": ["SM", "BDO", "ALI", "TEL"], "lat": 12.88, "lng": 121.77, "commodities": ["Electronics", "Coconut Oil", "Bananas", "Nickel", "Copper", "Gold", "BPO Services"], "ports": ["Port of Manila", "Port of Cebu"]},
    {"code": "VN", "name": "Vietnam", "region": "Asia Pacific", "stockExchange": "HOSE", "currency": "VND", "currencySymbol": "₫", "tickers": ["VIC", "VHM", "TCB", "HPG"], "lat": 14.06, "lng": 108.28, "commodities": ["Rice", "Coffee", "Textiles", "Electronics", "Seafood", "Rubber"], "ports": ["Port of Ho Chi Minh City", "Port of Hai Phong", "Port of Da Nang"]},
    {"code": "NZ", "name": "New Zealand", "region": "Asia Pacific", "stockExchange": "NZX", "currency": "NZD", "currencySymbol": "NZ$", "tickers": ["FPH", "A2M", "ATM", "SPK"], "lat": -40.90, "lng": 174.89, "commodities": ["Dairy", "Meat", "Wine", "Wool", "Timber", "Fish", "Fruit"], "ports": ["Port of Auckland", "Port of Tauranga"]},
    {"code": "AE", "name": "UAE", "region": "Middle East & Africa", "stockExchange": "ADX / DFM", "currency": "AED", "currencySymbol": "د.إ", "marketCap": "$720B", "tickers": ["ADNOC", "EMAAR", "DEWA", "FAB"], "lat": 23.42, "lng": 53.85, "commodities": ["Oil", "Natural Gas", "Gold", "Aluminum", "Petrochemicals", "Tourism", "Logistics"], "ports": ["Port of Jebel Ali", "Port of Khalifa", "Port of Zayed"]},
    {"code": "SA", "name": "Saudi Arabia", "region": "Middle East & Africa", "stockExchange": "Tadawul", "currency": "SAR", "currencySymbol": "﷼", "marketCap": "$2.7T", "tickers": ["ARAMCO", "SNB", "ALRAJHI", "STC", "SABIC"], "lat": 23.89, "lng": 45.08, "commodities": ["Oil", "Natural Gas", "Petrochemicals", "Gold", "Fertilizer", "Desalination"], "ports": ["Port of Jeddah", "King Abdulaziz Port (Dammam)", "Port of Jubail"]},
    {"code": "QA", "name": "Qatar", "region": "Middle East & Africa", "stockExchange": "QSE", "currency": "QAR", "currencySymbol": "﷼", "tickers": ["QNB", "QATAR", "MASRAF"], "lat": 25.35, "lng": 51.18, "commodities": ["LNG", "Oil", "Petrochemicals", "Fertilizer", "Steel"], "ports": ["Port of Hamad", "Port of Doha"]},
    {"code": "KW", "name": "Kuwait", "region": "Middle East & Africa", "stockExchange": "Boursa Kuwait", "currency": "KWD", "currencySymbol": "د.ك", "tickers": ["NBK", "ZAIN", "KFH"], "lat": 29.31, "lng": 47.48, "commodities": ["Oil", "Natural Gas", "Petrochemicals", "Fertilizer"], "ports": ["Port of Shuwaikh", "Port of Shuaiba"]},
    {"code": "IL", "name": "Israel", "region": "Middle East & Africa", "stockExchange": "TASE", "currency": "ILS", "currencySymbol": "₪", "marketCap": "$260B", "tickers": ["TEVA", "NICE", "WIX", "CHKP"], "lat": 31.05, "lng": 34.85, "commodities": ["Diamonds", "Pharmaceuticals", "Tech", "Citrus", "Natural Gas", "Chemicals"], "ports": ["Port of Haifa", "Port of Ashdod"]},
    {"code": "ZA", "name": "South Africa", "region": "Middle East & Africa", "stockExchange": "JSE", "currency": "ZAR", "currencySymbol": "R", "marketCap": "$900B", "tradingHours": "09:00-17:00 SAST", "tickers": ["NASPERS", "ANHEUSER", "FIRSTRAND", "STANDARD", "MTN"], "lat": -30.56, "lng": 22.94, "commodities": ["Gold", "Diamonds", "Platinum", "Coal", "Iron Ore", "Wine", "Corn", "Chromium"], "ports": ["Port of Durban", "Port of Cape Town", "Port of Richards Bay"]},
    {"code": "NG", "name": "Nigeria", "region": "Middle East & Africa", "stockExchange": "NGX", "currency": "NGN", "currencySymbol": "₦", "tickers": ["DANGOTE", "MTNN", "ZENITH", "ACCESS"], "lat": 9.08, "lng": 8.68, "commodities": ["Oil", "Natural Gas", "Cocoa", "Rubber", "Gold", "Cassava"], "ports": ["Port of Lagos", "Port of Port Harcourt"]},
    {"code": "KE", "name": "Kenya", "region": "Middle East & Africa", "stockExchange": "NSE", "currency": "KES", "currencySymbol": "KSh", "tickers": ["SCOM", "EABL", "KCB"], "lat": -0.02, "lng": 37.91, "commodities": ["Tea", "Coffee", "Horticulture", "Tourism", "Flowers"], "ports": ["Port of Mombasa"]},
    {"code": "EG", "name": "Egypt", "region": "Middle East & Africa", "stockExchange": "EGX", "currency": "EGP", "currencySymbol": "E£", "tickers": ["COMI", "EFG", "HRHO", "TMGH"], "lat": 26.82, "lng": 30.80, "commodities": ["Oil", "Natural Gas", "Cotton", "Gold", "Phosphates", "Tourism"], "ports": ["Port of Alexandria", "Port of Damietta", "Suez Canal"]},
    {"code": "MA", "name": "Morocco", "region": "Middle East & Africa", "stockExchange": "Casablanca SE", "currency": "MAD", "currencySymbol": "MAD", "tickers": ["ATW", "IAM", "BCP", "LQ"], "lat": 31.79, "lng": -7.09, "commodities": ["Phosphates", "Fish", "Olive Oil", "Fruit", "Automotive", "Renewable Energy"], "ports": ["Port of Casablanca", "Port of Tangier"]},
    {"code": "MU", "name": "Mauritius", "region": "Middle East & Africa", "stockExchange": "SEM", "currency": "MUR", "currencySymbol": "Rs", "tickers": ["MCB", "SBM", "NMH"], "lat": -20.35, "lng": 57.55, "commodities": ["Sugar", "Textiles", "Tourism", "Financial Services"], "ports": ["Port of Port Louis"]},
    {"code": "PK", "name": "Pakistan", "region": "Asia Pacific", "stockExchange": "PSX", "currency": "PKR", "currencySymbol": "Rs", "marketCap": "$35B", "tickers": ["OGDC", "MCB", "POL", "ENGRO"], "lat": 30.38, "lng": 69.35, "commodities": ["Textiles", "Rice", "Wheat", "Cotton", "Sugar", "Fruit", "Leather"], "ports": ["Port of Karachi", "Port of Qasim", "Gwadar Port"]},
    {"code": "IR", "name": "Iran", "region": "Middle East & Africa", "stockExchange": "TSE", "currency": "IRR", "currencySymbol": "﷼", "tickers": ["TSM", "FARS", "MOBILE"], "lat": 32.43, "lng": 53.69, "commodities": ["Oil", "Natural Gas", "Petrochemicals", "Steel", "Copper", "Pistachios", "Carpets"], "ports": ["Port of Bandar Abbas", "Port of Imam Khomeini"]},
]

COUNTRIES_BY_CODE = {c["code"]: c for c in COUNTRIES}

TRADE_ROUTES = [
    {"from": "US", "to": "CN", "value": "$558B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 35.86, "toLng": 104.19, "color": "#00d4ff"},
    {"from": "US", "to": "MX", "value": "$415B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 23.63, "toLng": -102.55, "color": "#00ff88"},
    {"from": "US", "to": "CA", "value": "$382B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 56.13, "toLng": -106.35, "color": "#00d4ff"},
    {"from": "US", "to": "JP", "value": "$208B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 36.20, "toLng": 138.25, "color": "#00d4ff"},
    {"from": "US", "to": "DE", "value": "$190B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 51.17, "toLng": 10.45, "color": "#00d4ff"},
    {"from": "US", "to": "GB", "value": "$260B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 55.38, "toLng": -3.44, "color": "#00ff88"},
    {"from": "US", "to": "KR", "value": "$165B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 35.91, "toLng": 127.77, "color": "#00d4ff"},
    {"from": "US", "to": "IN", "value": "$146B", "fromLat": 37.09, "fromLng": -95.71, "toLat": 20.59, "toLng": 78.96, "color": "#00d4ff"},
    {"from": "CN", "to": "JP", "value": "$348B", "fromLat": 35.86, "fromLng": 104.19, "toLat": 36.20, "toLng": 138.25, "color": "#00ff88"},
    {"from": "CN", "to": "KR", "value": "$312B", "fromLat": 35.86, "fromLng": 104.19, "toLat": 35.91, "toLng": 127.77, "color": "#00ff88"},
    {"from": "CN", "to": "DE", "value": "$245B", "fromLat": 35.86, "fromLng": 104.19, "toLat": 51.17, "toLng": 10.45, "color": "#ffaa00"},
    {"from": "CN", "to": "AU", "value": "$207B", "fromLat": 35.86, "fromLng": 104.19, "toLat": -25.27, "toLng": 133.77, "color": "#ffaa00"},
    {"from": "CN", "to": "RU", "value": "$190B", "fromLat": 35.86, "fromLng": 104.19, "toLat": 61.52, "toLng": 105.32, "color": "#ffaa00"},
    {"from": "CN", "to": "BR", "value": "$152B", "fromLat": 35.86, "fromLng": 104.19, "toLat": -14.24, "toLng": -51.93, "color": "#ffaa00"},
    {"from": "DE", "to": "NL", "value": "$195B", "fromLat": 51.17, "fromLng": 10.45, "toLat": 52.13, "toLng": 5.29, "color": "#00d4ff"},
    {"from": "DE", "to": "FR", "value": "$182B", "fromLat": 51.17, "fromLng": 10.45, "toLat": 46.60, "toLng": 1.89, "color": "#00d4ff"},
    {"from": "DE", "to": "CN", "value": "$245B", "fromLat": 51.17, "fromLng": 10.45, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "JP", "to": "KR", "value": "$142B", "fromLat": 36.20, "fromLng": 138.25, "toLat": 35.91, "toLng": 127.77, "color": "#00ff88"},
    {"from": "JP", "to": "AU", "value": "$125B", "fromLat": 36.20, "fromLng": 138.25, "toLat": -25.27, "toLng": 133.77, "color": "#00ff88"},
    {"from": "GB", "to": "US", "value": "$260B", "fromLat": 55.38, "fromLng": -3.44, "toLat": 37.09, "toLng": -95.71, "color": "#00ff88"},
    {"from": "GB", "to": "DE", "value": "$155B", "fromLat": 55.38, "fromLng": -3.44, "toLat": 51.17, "toLng": 10.45, "color": "#00d4ff"},
    {"from": "GB", "to": "NL", "value": "$130B", "fromLat": 55.38, "fromLng": -3.44, "toLat": 52.13, "toLng": 5.29, "color": "#00d4ff"},
    {"from": "IN", "to": "AE", "value": "$105B", "fromLat": 20.59, "fromLng": 78.96, "toLat": 23.42, "toLng": 53.85, "color": "#ffaa00"},
    {"from": "IN", "to": "US", "value": "$146B", "fromLat": 20.59, "fromLng": 78.96, "toLat": 37.09, "toLng": -95.71, "color": "#00d4ff"},
    {"from": "RU", "to": "DE", "value": "$135B", "fromLat": 61.52, "fromLng": 105.32, "toLat": 51.17, "toLng": 10.45, "color": "#ff4444"},
    {"from": "RU", "to": "CN", "value": "$190B", "fromLat": 61.52, "fromLng": 105.32, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "SA", "to": "CN", "value": "$120B", "fromLat": 23.89, "fromLng": 45.08, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "SA", "to": "US", "value": "$85B", "fromLat": 23.89, "fromLng": 45.08, "toLat": 37.09, "toLng": -95.71, "color": "#ffaa00"},
    {"from": "BR", "to": "CN", "value": "$152B", "fromLat": -14.24, "fromLng": -51.93, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "AU", "to": "CN", "value": "$207B", "fromLat": -25.27, "fromLng": 133.77, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "AU", "to": "JP", "value": "$125B", "fromLat": -25.27, "fromLng": 133.77, "toLat": 36.20, "toLng": 138.25, "color": "#00ff88"},
    {"from": "KR", "to": "CN", "value": "$312B", "fromLat": 35.91, "fromLng": 127.77, "toLat": 35.86, "toLng": 104.19, "color": "#00ff88"},
    {"from": "KR", "to": "US", "value": "$165B", "fromLat": 35.91, "fromLng": 127.77, "toLat": 37.09, "toLng": -95.71, "color": "#00d4ff"},
    {"from": "SG", "to": "CN", "value": "$140B", "fromLat": 1.35, "fromLng": 103.82, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "MY", "to": "SG", "value": "$95B", "fromLat": 4.21, "fromLng": 101.98, "toLat": 1.35, "toLng": 103.82, "color": "#00ff88"},
    {"from": "ID", "to": "CN", "value": "$110B", "fromLat": -0.79, "fromLng": 113.92, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "AE", "to": "IN", "value": "$105B", "fromLat": 23.42, "fromLng": 53.85, "toLat": 20.59, "toLng": 78.96, "color": "#ffaa00"},
    {"from": "NG", "to": "US", "value": "$25B", "fromLat": 9.08, "fromLng": 8.68, "toLat": 37.09, "toLng": -95.71, "color": "#ff4444"},
    {"from": "ZA", "to": "CN", "value": "$75B", "fromLat": -30.56, "fromLng": 22.94, "toLat": 35.86, "toLng": 104.19, "color": "#ffaa00"},
    {"from": "TR", "to": "DE", "value": "$68B", "fromLat": 38.96, "fromLng": 35.24, "toLat": 51.17, "toLng": 10.45, "color": "#ffaa00"},
]

MILITARY_RELATIONS = [
    {"countryA": "US", "countryB": "GB", "type": "alliance", "label": "NATO - Five Eyes", "fromLat": 37.09, "fromLng": -95.71, "toLat": 55.38, "toLng": -3.44},
    {"countryA": "US", "countryB": "CA", "type": "alliance", "label": "NATO - NORAD", "fromLat": 37.09, "fromLng": -95.71, "toLat": 56.13, "toLng": -106.35},
    {"countryA": "US", "countryB": "DE", "type": "alliance", "label": "NATO Alliance", "fromLat": 37.09, "fromLng": -95.71, "toLat": 51.17, "toLng": 10.45},
    {"countryA": "US", "countryB": "FR", "type": "alliance", "label": "NATO Alliance", "fromLat": 37.09, "fromLng": -95.71, "toLat": 46.60, "toLng": 1.89},
    {"countryA": "US", "countryB": "JP", "type": "alliance", "label": "US-Japan Security Treaty", "fromLat": 37.09, "fromLng": -95.71, "toLat": 36.20, "toLng": 138.25},
    {"countryA": "US", "countryB": "KR", "type": "alliance", "label": "US-ROK Mutual Defense", "fromLat": 37.09, "fromLng": -95.71, "toLat": 35.91, "toLng": 127.77},
    {"countryA": "US", "countryB": "AU", "type": "alliance", "label": "ANZUS - AUKUS", "fromLat": 37.09, "fromLng": -95.71, "toLat": -25.27, "toLng": 133.77},
    {"countryA": "RU", "countryB": "CN", "type": "alliance", "label": "Strategic Partnership", "fromLat": 61.52, "fromLng": 105.32, "toLat": 35.86, "toLng": 104.19},
    {"countryA": "RU", "countryB": "IN", "type": "alliance", "label": "Defense Partnership", "fromLat": 61.52, "fromLng": 105.32, "toLat": 20.59, "toLng": 78.96},
    {"countryA": "CN", "countryB": "PK", "type": "alliance", "label": "China-Pakistan Alliance", "fromLat": 35.86, "fromLng": 104.19, "toLat": 30.38, "toLng": 69.35},
    {"countryA": "US", "countryB": "RU", "type": "rivalry", "label": "Geopolitical Rivalry", "fromLat": 37.09, "fromLng": -95.71, "toLat": 61.52, "toLng": 105.32},
    {"countryA": "US", "countryB": "CN", "type": "rivalry", "label": "Strategic Competition", "fromLat": 37.09, "fromLng": -95.71, "toLat": 35.86, "toLng": 104.19},
    {"countryA": "IN", "countryB": "CN", "type": "rivalry", "label": "Border Disputes", "fromLat": 20.59, "fromLng": 78.96, "toLat": 35.86, "toLng": 104.19},
    {"countryA": "IN", "countryB": "PK", "type": "conflict", "label": "Kashmir Conflict", "fromLat": 20.59, "fromLng": 78.96, "toLat": 30.38, "toLng": 69.35},
    {"countryA": "IL", "countryB": "IR", "type": "conflict", "label": "Regional Conflict", "fromLat": 31.05, "fromLng": 34.85, "toLat": 32.43, "toLng": 53.69},
    {"countryA": "RU", "countryB": "GB", "type": "rivalry", "label": "Strategic Rivalry", "fromLat": 61.52, "fromLng": 105.32, "toLat": 55.38, "toLng": -3.44},
    {"countryA": "CN", "countryB": "TW", "type": "conflict", "label": "Territorial Dispute", "fromLat": 35.86, "fromLng": 104.19, "toLat": 23.70, "toLng": 120.96},
    {"countryA": "KR", "countryB": "JP", "type": "neutral", "label": "Historical Tensions", "fromLat": 35.91, "fromLng": 127.77, "toLat": 36.20, "toLng": 138.25},
    {"countryA": "SA", "countryB": "IR", "type": "rivalry", "label": "Regional Proxy Conflict", "fromLat": 23.89, "fromLng": 45.08, "toLat": 32.43, "toLng": 53.69},
    {"countryA": "US", "countryB": "IL", "type": "alliance", "label": "Strategic Ally", "fromLat": 37.09, "fromLng": -95.71, "toLat": 31.05, "toLng": 34.85},
    {"countryA": "RU", "countryB": "TR", "type": "neutral", "label": "Competitive Cooperation", "fromLat": 61.52, "fromLng": 105.32, "toLat": 38.96, "toLng": 35.24},
    {"countryA": "FR", "countryB": "DE", "type": "alliance", "label": "EU Core - Franco-German", "fromLat": 46.60, "fromLng": 1.89, "toLat": 51.17, "toLng": 10.45},
    {"countryA": "GB", "countryB": "FR", "type": "alliance", "label": "NATO - Entente Cordiale", "fromLat": 55.38, "fromLng": -3.44, "toLat": 46.60, "toLng": 1.89},
]

PORTS = [
    {"countryCode": "US", "name": "Los Angeles", "lat": 33.74, "lng": -118.27, "volume": "major"},
    {"countryCode": "US", "name": "New York/New Jersey", "lat": 40.69, "lng": -74.04, "volume": "major"},
    {"countryCode": "US", "name": "Houston", "lat": 29.75, "lng": -95.10, "volume": "major"},
    {"countryCode": "US", "name": "Long Beach", "lat": 33.77, "lng": -118.22, "volume": "major"},
    {"countryCode": "US", "name": "Savannah", "lat": 32.02, "lng": -81.15, "volume": "major"},
    {"countryCode": "CN", "name": "Shanghai", "lat": 31.39, "lng": 121.50, "volume": "major"},
    {"countryCode": "CN", "name": "Shenzhen", "lat": 22.50, "lng": 113.90, "volume": "major"},
    {"countryCode": "CN", "name": "Ningbo-Zhoushan", "lat": 29.87, "lng": 122.20, "volume": "major"},
    {"countryCode": "CN", "name": "Guangzhou", "lat": 23.10, "lng": 113.25, "volume": "major"},
    {"countryCode": "CN", "name": "Qingdao", "lat": 36.06, "lng": 120.38, "volume": "major"},
    {"countryCode": "SG", "name": "Singapore", "lat": 1.27, "lng": 103.84, "volume": "major"},
    {"countryCode": "KR", "name": "Busan", "lat": 35.10, "lng": 129.04, "volume": "major"},
    {"countryCode": "KR", "name": "Incheon", "lat": 37.45, "lng": 126.60, "volume": "major"},
    {"countryCode": "JP", "name": "Tokyo", "lat": 35.65, "lng": 139.77, "volume": "major"},
    {"countryCode": "JP", "name": "Yokohama", "lat": 35.44, "lng": 139.64, "volume": "major"},
    {"countryCode": "JP", "name": "Osaka", "lat": 34.65, "lng": 135.43, "volume": "major"},
    {"countryCode": "JP", "name": "Nagoya", "lat": 35.08, "lng": 136.88, "volume": "major"},
    {"countryCode": "NL", "name": "Rotterdam", "lat": 51.91, "lng": 4.50, "volume": "major"},
    {"countryCode": "AE", "name": "Jebel Ali", "lat": 25.01, "lng": 55.06, "volume": "major"},
    {"countryCode": "MY", "name": "Port Klang", "lat": 3.00, "lng": 101.39, "volume": "major"},
    {"countryCode": "MY", "name": "Tanjung Pelepas", "lat": 1.37, "lng": 103.56, "volume": "major"},
    {"countryCode": "AU", "name": "Port Hedland", "lat": -20.31, "lng": 118.58, "volume": "major"},
    {"countryCode": "AU", "name": "Sydney", "lat": -33.86, "lng": 151.21, "volume": "major"},
    {"countryCode": "AU", "name": "Melbourne", "lat": -37.82, "lng": 144.97, "volume": "major"},
    {"countryCode": "IN", "name": "Mumbai", "lat": 18.91, "lng": 72.83, "volume": "major"},
    {"countryCode": "IN", "name": "Mundra", "lat": 22.84, "lng": 69.72, "volume": "major"},
    {"countryCode": "IN", "name": "Chennai", "lat": 13.09, "lng": 80.29, "volume": "major"},
    {"countryCode": "GB", "name": "Felixstowe", "lat": 51.95, "lng": 1.35, "volume": "major"},
    {"countryCode": "GB", "name": "Southampton", "lat": 50.90, "lng": -1.40, "volume": "major"},
    {"countryCode": "DE", "name": "Hamburg", "lat": 53.55, "lng": 9.97, "volume": "major"},
    {"countryCode": "DE", "name": "Bremen", "lat": 53.08, "lng": 8.80, "volume": "major"},
    {"countryCode": "BR", "name": "Santos", "lat": -23.97, "lng": -46.30, "volume": "major"},
    {"countryCode": "BR", "name": "Rio de Janeiro", "lat": -22.90, "lng": -43.20, "volume": "major"},
    {"countryCode": "BE", "name": "Antwerp", "lat": 51.25, "lng": 4.40, "volume": "major"},
    {"countryCode": "ES", "name": "Algeciras", "lat": 36.13, "lng": -5.45, "volume": "major"},
    {"countryCode": "ES", "name": "Barcelona", "lat": 41.33, "lng": 2.17, "volume": "major"},
    {"countryCode": "IT", "name": "Genoa", "lat": 44.40, "lng": 8.92, "volume": "major"},
    {"countryCode": "FR", "name": "Marseille", "lat": 43.33, "lng": 5.37, "volume": "major"},
    {"countryCode": "FR", "name": "Le Havre", "lat": 49.49, "lng": 0.11, "volume": "major"},
    {"countryCode": "SA", "name": "Jeddah", "lat": 21.49, "lng": 39.16, "volume": "major"},
    {"countryCode": "EG", "name": "Alexandria", "lat": 31.20, "lng": 29.92, "volume": "major"},
    {"countryCode": "ZA", "name": "Durban", "lat": -29.86, "lng": 31.03, "volume": "major"},
    {"countryCode": "ZA", "name": "Cape Town", "lat": -33.91, "lng": 18.42, "volume": "major"},
    {"countryCode": "ID", "name": "Tanjung Priok", "lat": -6.10, "lng": 106.88, "volume": "major"},
    {"countryCode": "TH", "name": "Laem Chabang", "lat": 13.07, "lng": 100.88, "volume": "major"},
    {"countryCode": "VN", "name": "Ho Chi Minh City", "lat": 10.77, "lng": 106.70, "volume": "major"},
    {"countryCode": "TW", "name": "Kaohsiung", "lat": 22.62, "lng": 120.27, "volume": "major"},
    {"countryCode": "MX", "name": "Manzanillo", "lat": 19.05, "lng": -104.32, "volume": "major"},
    {"countryCode": "CA", "name": "Vancouver", "lat": 49.29, "lng": -123.12, "volume": "major"},
    {"countryCode": "CA", "name": "Prince Rupert", "lat": 54.32, "lng": -130.33, "volume": "medium"},
    {"countryCode": "NG", "name": "Lagos", "lat": 6.43, "lng": 3.40, "volume": "major"},
    {"countryCode": "QA", "name": "Hamad", "lat": 24.78, "lng": 51.56, "volume": "major"},
    {"countryCode": "KW", "name": "Shuwaikh", "lat": 29.35, "lng": 47.93, "volume": "major"},
    {"countryCode": "IL", "name": "Haifa", "lat": 32.82, "lng": 34.99, "volume": "major"},
    {"countryCode": "IL", "name": "Ashdod", "lat": 31.83, "lng": 34.64, "volume": "major"},
    {"countryCode": "KE", "name": "Mombasa", "lat": -4.06, "lng": 39.66, "volume": "major"},
    {"countryCode": "HK", "name": "Hong Kong", "lat": 22.35, "lng": 114.11, "volume": "major"},
    {"countryCode": "PH", "name": "Manila", "lat": 14.58, "lng": 120.96, "volume": "major"},
    {"countryCode": "TR", "name": "Istanbul", "lat": 41.00, "lng": 28.97, "volume": "major"},
    {"countryCode": "MA", "name": "Tangier", "lat": 35.78, "lng": -5.81, "volume": "major"},
    {"countryCode": "EG", "name": "Suez Canal", "lat": 30.50, "lng": 32.55, "volume": "major"},
    {"countryCode": "GR", "name": "Piraeus", "lat": 37.94, "lng": 23.64, "volume": "major"},
    {"countryCode": "PL", "name": "Gdansk", "lat": 54.35, "lng": 18.65, "volume": "major"},
    {"countryCode": "PT", "name": "Sines", "lat": 37.96, "lng": -8.87, "volume": "medium"},
    {"countryCode": "FI", "name": "Helsinki", "lat": 60.17, "lng": 24.95, "volume": "medium"},
    {"countryCode": "IE", "name": "Dublin", "lat": 53.35, "lng": -6.20, "volume": "medium"},
    {"countryCode": "MU", "name": "Port Louis", "lat": -20.16, "lng": 57.50, "volume": "medium"},
    {"countryCode": "NZ", "name": "Auckland", "lat": -36.84, "lng": 174.76, "volume": "major"},
    {"countryCode": "NZ", "name": "Tauranga", "lat": -37.65, "lng": 176.17, "volume": "medium"},
]

LIVE_EVENTS = [
    {"id": 1, "title": "US Fed Signals Rate Cut", "description": "Federal Reserve hints at dovish stance amid slowing inflation.", "event_type": "economic", "severity": "medium", "status": "ongoing", "event_date": "2026-06-16T10:00:00Z", "source": "US"},
    {"id": 2, "title": "Russia Energy Sanctions Escalate", "description": "New EU sanctions target Russian oil exports, supply concerns rise.", "event_type": "geopolitical", "severity": "high", "status": "ongoing", "event_date": "2026-06-16T08:00:00Z", "source": "EU"},
    {"id": 3, "title": "China Tech Sector Rally", "description": "Hang Seng Tech index surges 4% on regulatory easing expectations.", "event_type": "market", "severity": "medium", "status": "ongoing", "event_date": "2026-06-16T06:00:00Z", "source": "CN"},
    {"id": 4, "title": "Middle East Tensions Rise", "description": "Geopolitical risks spike after military escalation in the region.", "event_type": "geopolitical", "severity": "high", "status": "ongoing", "event_date": "2026-06-16T04:00:00Z", "source": "IR"},
    {"id": 5, "title": "India GDP Growth Beats Estimates", "description": "Q3 GDP expands 7.2%, driven by manufacturing and services.", "event_type": "economic", "severity": "positive", "status": "ongoing", "event_date": "2026-06-16T02:00:00Z", "source": "IN"},
    {"id": 6, "title": "Oil Prices Volatile", "description": "Brent crude swings 3% amid conflicting supply signals from OPEC+.", "event_type": "market", "severity": "medium", "status": "ongoing", "event_date": "2026-06-16T00:00:00Z", "source": "Global"},
    {"id": 7, "title": "European Markets Mixed", "description": "Stoxx 600 fluctuates as investors weigh earnings against ECB outlook.", "event_type": "market", "severity": "medium", "status": "ongoing", "event_date": "2026-06-15T22:00:00Z", "source": "EU"},
    {"id": 8, "title": "Japan Nikkei Hits 5-Year High", "description": "BoJ maintains accommodative stance, weakening yen boosts exports.", "event_type": "market", "severity": "positive", "status": "ongoing", "event_date": "2026-06-15T20:00:00Z", "source": "JP"},
    {"id": 9, "title": "UK Inflation Drops Below Target", "description": "BoE considers rate cuts as CPI falls to 1.8%.", "event_type": "economic", "severity": "positive", "status": "ongoing", "event_date": "2026-06-15T18:00:00Z", "source": "GB"},
    {"id": 10, "title": "Brazil Central Bank Holds Rates", "description": "Selic rate maintained at 13.75% amid fiscal uncertainty.", "event_type": "economic", "severity": "medium", "status": "ongoing", "event_date": "2026-06-15T16:00:00Z", "source": "BR"},
]
